framework:
    workflows:
        file_process:
            type: state_machine
            marking-store:
              type: 'method'
              property: 'status'
            supports:
              - App\Entity\File
            initial-marking: pending
            places:
            - pending
            - error
            - processed
            transitions:
                processing:
                      from: pending
                      to: processed
                retry:
                      from: error
                      to: pending