framework:
    workflows:
        file_process:
            type: workflow
            marking-store:
              type: 'method'
              property: 'status'
            supports:
              - App\Entity\File
            initial-marking: pending
            places:
            - input
            - pending
            - error
            - processed

            transitions:
                execute:
                      from: input
                      to: pending
                processing:
                      from: pending
                      to: [processed, error]
                reprocess:
                      from: error
                      to: pending