framework:
    workflows:
        file_process:
            type: state_machine
            places:
            - pending
            - error
            - processed
            transitions:
                - processing:
                      from: pending
                      to:
                          - error
                          - processed
                - retry:
                      from: error
                      to: pending