version: '3'
services:
  php:
    build: .docker/php
    container_name: sf4_php
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: sf4_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sf4_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
    links:
      - mysql